### ISSUE TITLE
Excellent cheat, starred for the same, but how to reverse

### ISSUE THREAD

**Issue by HackaTunes** [danielkrupinski/OneByteWallhack#13]
This cheat is excellent, but how to reverse this cheat to normal? I cant figure out. Please help me

**Comment by FrankFeenix** [comment]
Maybe just delete those files?

**Comment by fernandom241** [comment]
same question, but maybe you can try to uninstall and redownload CSGO

**Comment by HackaTunes** [comment]
Got it.
