### ISSUE TITLE
Faceit Support?

### ISSUE THREAD

**Issue by dyinginslowmotion** [danielkrupinski/OneByteWallhack#35]
just wondering if this python script work in faceit?

**Comment by vlc3n** [comment]
without client it should work yes

**Comment by noob9303** [comment]
Do you mean without faceit anticheat?

**Comment by Sarahsqueaks** [comment]
are you stupid?

**Comment by noob9303** [comment]
> are you stupid?

it dont work with faceit ac client

**Comment by Sarahsqueaks** [comment]
> > are you stupid?
> 
> 
> 
> it dont work with faceit ac client
> 
> 

i'm calling the OP stupid for thinking that it would work with faceit

**Comment by dyinginslowmotion** [comment]
> 

stop being toxic..
